apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  targetNamespace: loki
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
    loki:
      auth_enabled: false
      storage:
        type: filesystem
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
    monitoring:
      enabled: false
