apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.70.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-k8s
