apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: agent
  namespace: otel
spec:
  mode: daemonset
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 256Mi
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu: {}
          load: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}

    processors:
      batch:
        timeout: 10s

    exporters:
      otlp:
        endpoint: gateway-collector.otel.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      telemetry:
        metrics:
          readers:
            - periodic:
                exporter:
                  prometheus:
                    host: "0.0.0.0"
                    port: 8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [batch]
          exporters: [otlp]